# Generated by Django 5.0.8 on 2024-08-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hava", "0002_weatherdata_delete_weather"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="cloudiness",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="sunrise",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="sunset",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temperature_max",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temperature_min",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="visibility",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="city",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="pressure",
            field=models.FloatField(),
        ),
    ]
