# Generated by Django 5.0.8 on 2024-08-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hava", "0003_remove_weatherdata_last_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="cloudiness",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="sunrise",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="sunset",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="visibility",
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="icon",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature_max",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature_min",
            field=models.FloatField(),
        ),
    ]
