# Generated by Django 5.0.8 on 2024-08-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hava", "0004_remove_weatherdata_cloudiness_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="icon",
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="city_slug",
            field=models.SlugField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="city",
            field=models.CharField(max_length=100),
        ),
    ]
